#!/bin/bash

sleep 15

psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE DATABASE $POSTGRES_DB_HUB;"
psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE USER $POSTGRES_USER_HUB WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD_HUB';"
psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB_HUB TO $POSTGRES_USER_HUB;"
